SELECT * 
FROM neatapp  

-- 1. Which apps have the highest rating in the given available dataset?

SELECT App, Rating
FROM neatapp 
WHERE Rating = '5.0'
LIMIT 10;

--2.	What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.

SELECT App, Rating, Installs, Reviews
FROM neatapp 
WHERE Rating = '5.0'
ORDER BY Reviews DESC 
LIMIT 10 


-- 3.	Which app has the highest number of reviews? Also, mention the number of reviews and category of the app

SELECT App, Reviews, Category
FROM neatapp 
ORDER BY Reviews DESC
LIMIT 1


--4. What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)

SELECT Sum(Price) * Sum(Installs) AS total_app_revenue
FROM neatapp  
WHERE TYPE ='Paid' and Price !='0.0'
  

--5. Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category

SELECT Category, SUM(Installs) AS total_installs
FROM neatapp
GROUP BY Category
ORDER BY total_installs DESC 
LIMIT 1


--6.	Which Genre has the most number of published apps?

SELECT Genres, COUNT(Genres) AS app_count
FROM neatapp  
GROUP BY Genres
ORDER BY app_count DESC 


--7.Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top (to avoid duplicate results use distinct

SELECT DISTINCT Category,Installs
FROM neatapp  
WHERE Category='GAME'
ORDER BY Installs DESC 
LIMIT 10


-- 8) Provide the list of apps that can work on android version 4.0.3 and UP.
SELECT App, "Android Ver" 
FROM neatapp  
WHERE "Android Ver"  ='4.0.3 and up'

--9)How many apps from the given data set are free? Also, provide the number of paid apps

SELECT COUNT(*) AS Free_apps 
FROM neatapp 
WHERE Type = 'Free'

SELECT COUNT(*) AS Paid_apps 
FROM neatapp 
WHERE Type = 'Paid'

--OR

SELECT 
SUM(CASE WHEN Type = 'Free' THEN 1 ELSE 0 END) AS Free_apps,
SUM(CASE WHEN Type = 'Paid' THEN 1 ELSE 0 END) AS Paid_apps
FROM neatapp  

--10 Which is the best dating app? (Best dating app is the one having the highest number of Reviews)


SELECT App,Genres, Reviews
FROM neatapp  
WHERE Genres= 'Dating'
ORDER BY Reviews DESC 
LIMIT 10


--11.Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app 10 best foods for you and compare them.


SELECT 
    SUM(CASE WHEN Sentiment = 'Positive' THEN 1 ELSE 0 END) AS total_positive_reviews_apps,
    SUM(CASE WHEN Sentiment = 'Negative' THEN 1 ELSE 0 END) AS total_negative_reviews_apps
FROM 
    playstore_reviews 
WHERE 
    App = '10 Best Foods for You';


   --12.	Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
   
   SELECT Translated_Review FROM playstore_reviews
   where App ='ASUS SuperNote' and Sentiment_Polarity='1.0' and Sentiment_Subjectivity ='1.0'
   
   
   --13.	Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 
   
   
   SELECT App,Sentiment 
   FROM playstore_reviews
   where App ='Abs Training-Burn belly fat' and Sentiment='Neutral'
   
   
--14 Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity
   
   SELECT App,Sentiment 
   FROM playstore_reviews 
   where app ='Adobe Acrobat Reader' and Sentiment='Negative'
   
   

